import { 
  FaFacebook, FaTwitter, FaInstagram, FaLinkedin, FaPinterest, FaYoutube, FaSnapchat, FaTiktok, FaWhatsapp, FaReddit, 
  FaTumblr, FaFlickr, FaQuora, FaWeixin, FaViber, FaLine, FaSkype, FaTelegram, FaFacebookMessenger, FaDiscord, FaMedium, 
  FaVimeo, FaDribbble, FaBehance, FaSlack, FaGithub, FaStackOverflow, FaRss, FaBlogger, FaWordpress, FaSoundcloud, 
  FaSpotify, FaApple, FaGoogle, FaPeriscope, FaFoursquare, FaYelp, FaTwitch, FaMeetup, FaXing, FaDigg, 
  FaDelicious, FaVine, FaQq, FaVk
} from 'react-icons/fa';

export const iconComponents = {
  Facebook: FaFacebook,
  Twitter: FaTwitter,
  Instagram: FaInstagram,
  LinkedIn: FaLinkedin,
  Pinterest: FaPinterest,
  YouTube: FaYoutube,
  Snapchat: FaSnapchat,
  TikTok: FaTiktok,
  WhatsApp: FaWhatsapp,
  Reddit: FaReddit,
  Tumblr: FaTumblr,
  Flickr: FaFlickr,
  Quora: FaQuora,
  WeChat: FaWeixin,
  Viber: FaViber,
  Line: FaLine,
  Skype: FaSkype,
  Telegram: FaTelegram,
  Messenger: FaFacebookMessenger,
  Discord: FaDiscord,
  Medium: FaMedium,
  Vimeo: FaVimeo,
  Dribbble: FaDribbble,
  Behance: FaBehance,
  Slack: FaSlack,
  GitHub: FaGithub,
  'Stack Overflow': FaStackOverflow,
  RSS: FaRss,
  Blogger: FaBlogger,
  WordPress: FaWordpress,
  SoundCloud: FaSoundcloud,
  Spotify: FaSpotify,
  'Apple Music': FaApple,
  Google: FaGoogle,
  Periscope: FaPeriscope,
  Foursquare: FaFoursquare,
  Yelp: FaYelp,
  Twitch: FaTwitch,
  Meetup: FaMeetup,
  Xing: FaXing,
  Digg: FaDigg,
  Delicious: FaDelicious,
  Vine: FaVine,
  QQ: FaQq,
  VK: FaVk,
};

export const iconNames = [
  "Facebook",
  "Twitter",
  "Instagram",
  "LinkedIn",
  "Pinterest",
  "YouTube",
  "Snapchat",
  "TikTok",
  "WhatsApp",
  "Reddit",
  "Tumblr",
  "Flickr",
  "Quora",
  "WeChat",
  "Viber",
  "Line",
  "Skype",
  "Telegram",
  "Messenger",
  "Discord",
  "Medium",
  "Vimeo",
  "Dribbble",
  "Behance",
  "Slack",
  "GitHub",
  "Stack Overflow",
  "RSS",
  "Blogger",
  "WordPress",
  "SoundCloud",
  "Spotify",
  "Apple Music",
  "Google",
  "Periscope",
  "Foursquare",
  "Myspace",
  "Yelp",
  "Twitch",
  "Meetup",
  "Xing",
  "Digg",
  "Delicious",
  "Vine",
  "QQ",
  "VK",
  "Douban"
];
